export const LOGIN_USER_START='LOGIN_USER_START'
export const LOGIN_USER_SUCCESS='LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAIL='LOGIN_USER_FAIL'

export const CREATE_USER_START='CREATE_USER_START'
export const CREATE_USER_SUCCESS='CREATE_USER_SUCCESS'
export const CREATE_USER_FAIL='CREATE_USER_FAIL'

export const USER_SIGNOUT= "USER_SIGNOUT"

export const ALL_USER_FETCH_START='ALL_USER_FETCH_START'
export const ALL_USER_FETCH_SUCCESS='ALL_USER_FETCH_SUCCESS'
export const ALL_USER_FETCH_FAIL='ALL_USER_FETCH_FAIL'

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET';

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST';
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS';
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL';
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET';

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL';
export const USER_DELETE_RESET = 'USER_DELETE_RESET';
